### ISSUE TITLE
Disable drag when only click on some elements like image or video

### ISSUE THREAD

**Issue by skywalker1905** [davidparsson/scrollbar-anywhere#52]
Hi, thank you for develop this extensions, it very easy and convenient, and I found an issue here:

When I click on some elements like image or video with my mouse or surface pen, it should be zoom or play, but with this extension, it can not trigger this event but only scroll happen, can this extension only capture events when mouse move more than 1 pixel?
I can hold a key to disable it when I want click on a image or a video, but sometimes I don't have a keyboard with my surface.

My setup:
- Mouse button used when scrolling: use left button to  trigger the scroll, so I can use this extension not only with my mouse, but also with my surface pen, it's excellent experience with the pen.
many website can reproduce this issue like www.quora.com, when click on an answer, it will not popup when this extension enable.
- Chrome version:  56.0.2924.21 beta (64-bit)
- Operating system: Windows 10

**Comment by skywalker1905** [comment]
After I restart my computer and open chrome again, this issue can not reproduce again, it's very strange, may be it can mark as closed now, thank you.

**Comment by davidparsson** [comment]
I'm glad it works!

**Comment by Droyk** [comment]
Don't close this issue because it definitely will come back I think developer need to make this extension compatible with many sites because I have seen many sites that scrollbar isn't compatible at all 

I want some features 

- **Exclude this site feature implementation** (this will work when the site isn't compatible with scrollbar at all isn't compatible means scrollbar only scrolls on the page and doesn't interact with elements of the page.)
- **Add more buttons to hold down to drag** means rightnow scrollbar only supports 3 mouse buttons right, middle & left I want you to give use more mouse buttons so I can drag whenever I want to without being afraid of site compatibility I have 6 mouse buttons which means 3 are the main middle, left & right and other 3 are not that main so in short if you implement this feature I will leave my 3 main buttons and with 3 buttons that are not my main buttons so this means there is no worry of site compatibility.

**Comment by Droyk** [comment]
Don't close this issue @skywalker1905 because it definitely will come back I think developer need to make this extension compatible with many sites because I have seen many sites that scrollbar isn't compatible at all 

I want some features 

- **Exclude this site feature implementation** (this will work when the site isn't compatible with scrollbar at all isn't compatible means scrollbar only scrolls on the page and doesn't interact with elements of the page.)
- **Add more buttons to hold down to drag** means rightnow scrollbar only supports 3 mouse buttons right, middle & left I want you to give use more mouse buttons so I can drag whenever I want to without being afraid of site compatibility I have 6 mouse buttons which means 3 are the main middle, left & right and other 3 are not that main so in short if you implement this feature I will leave my 3 main buttons and drag with 3 buttons that are not my main buttons so this means there is no worry of site compatibility.
