### ISSUE TITLE
reverting to 2.16 on Chrome Web Store

### ISSUE THREAD

**Issue by howardRaul1** [davidparsson/scrollbar-anywhere#80]
The latest version 3.0 doesn't work...and it has been deployed to the Chrome Web Store. 

The extension cannot be toggled on and off properly.

Can we revert to version 2.16 on the Chrome Web Store please?

**Comment by davidparsson** [comment]
Thanks for reporting @howardRaul1, and sorry for the inconvenience. 

Is it just the toggling that does not work, or anything else as well? What is the difference between expected and actual behaviour?

Chrome has enforced changes on extensions like this one, that required significant rework of the internals. 2.16 will soon stop working completely, so rolling back is not an ideal solution unless the fix is very complicated.

**Comment by howardRaul1** [comment]
Hi @davidparsson ,

It's just the toggling that does not work.  By default, the extension is toggled off.  Because the whole extension cannot be toggled on, so this means that the extension (at v3.0) cannot be used.

**Expected Behaviour**: Clicking on the extension icon on the toolbar should enable/disable the extension.

**Actual Behaviour**: Clicking on the extension icon on the toolbar does nothing.  The extension stays disabled all the time.  I have to load v2.16 in developer mode whenever I want to use the extension.

**Things I have tried**: I have tried this on the latest versions of Chrome and Edge.  I have also tried enabling the extension via the shortcut (configured at chrome://extensions/shortcuts), but I still cannot enable the extension.

**Comment by davidparsson** [comment]
Thanks, perfect.

I have been able to reproduce the issue, find the cause and fix it. I have submitted 3.1 for review to the Chrome Web Store, and once it's reviewed you should be able to use the extension again. Sorry for the inconvenience!

**Comment by davidparsson** [comment]
@howardRaul1, 3.1 is now released on Chrome Web Store. Please let me know if this resolved your issues or not.

**Comment by howardRaul1** [comment]
Resolved!  Thanks David!   Great extension!
